---
# This playbook deploys a set of Jenkins slaves to test various Hibernate projects
# It also deploys the basic setup for the Jenkins master node, but most
# configuration of this node is not automated.

- hosts: cislaves
  remote_user: fedora
  become: yes

  roles:
    - common
    - os1
    - jenkins-slave
    - postgres-server
    - mariadb-server
    - redis-server
    - neo4j-server
    - cockroachdb-server

- hosts: awscislaves
  remote_user: fedora
  become: yes

  roles:
    - common
    - jenkins-slave
    - awsslave
    - postgres-server
    - mariadb-server
    - redis-server
    - neo4j-server
    - cockroachdb-server


- hosts: cimaster
  remote_user: ec2-user
  become: yes

  roles:
    - common
    - aws
    - jenkins
    - inrelationto
    - temporary-inrelationto-staging

- hosts: dedicated
  remote_user: fedora
  become: yes

  roles:
    - common
    - os1
    - jenkins-dedicated
    - postgres-server
    - mariadb-server
