---
# This playbook can set up:
# - A Jenkins coordinator node, though most of the Jenkins configuration is still manual.
# - A Jenkins worker node, though most of the Jenkins configuration is still manual.
# - A hibernate.org/in.relation.to website node.

- hosts: jenkins-worker
  remote_user: fedora
  become: yes
  roles:
    - common
    - aws
    - jenkins-common
    - jenkins-worker
    - jenkins-worker-aws

- hosts: jenkins-coordinator
  remote_user: ec2-user
  become: yes
  pre_tasks:
    - name: Install Jenkins repo
      ansible.builtin.import_tasks: tasks/repo/jenkins.yml
  roles:
    - common
    - aws
    - jenkins-common
    - jenkins-coordinator

- hosts: websites
  remote_user: ec2-user
  become: yes
  roles:
    - common
    - aws
    - websites
