[storage]
driver = "overlay"
# This matches your Docker "data-root"
graphroot = "/mnt/workdir/containers"

[storage.options]
# This addresses your "No space left on device" error specifically
# It forces Podman to use the big drive for staging big blobs
image_copy_tmp_dir = "/mnt/workdir/tmp"