#!/bin/bash
# NOTE: each single whitespace and newline close to the template is important!
# - the script might stop to request an interactive confirmation of the host signature
# - it's expected to run this as user 'jenkins' as it will have the right keys setup 

transfer() {
   rsync --delete-during --archive --compress --progress --human-readable --one-file-system --stats ~/jboss-releases.txt $DESTINATION:~
   rsync --delete-during --archive --compress --progress --human-readable --one-file-system --stats ~/jdk* $DESTINATION:~
   rsync --delete-during --archive --compress --progress --human-readable --one-file-system --stats ~/.m2/settings* $DESTINATION:~/.m2
}

for DESTINATION in {% for host in groups['cislaves'] %}"{{ host }}" {% endfor %}

do
   transfer
done
