#!/bin/bash
# NOTE: each single whitespace and newline close to the template is important!
# - the script might stop to request an interactive confirmation of the host signature
# - it's expected to run this as user 'jenkins' as it will have the right keys setup 

transfer() {
   rsync --delete-during --archive --compress --progress --human-readable --one-file-system --stats --links ~/jboss-releases.txt $DESTINATION:~
   rsync --delete-during --archive --compress --progress --human-readable --one-file-system --stats --links --exclude 'jdk-1.6' ~/jdk* $DESTINATION:~
   rsync --delete-during --archive --compress --progress --human-readable --one-file-system --stats --copy-links ~/jdk-1.6 $DESTINATION:~
   rsync --delete-during --archive --compress --progress --human-readable --one-file-system --stats --links ~/.m2/settings* $DESTINATION:~/.m2
   rsync --delete-during --archive --compress --progress --human-readable --one-file-system --stats --links ~/apache-maven-* $DESTINATION:~
}

for DESTINATION in {% for host in groups['cislaves'] %}"{{ host }}" {% endfor %}

do
   transfer
done

for DESTINATION in {% for host in groups['awscislaves'] %}"{{ hostvars[host]['private_ip'] }}" {% endfor %}

do
   transfer
done
