#!/bin/bash
# NOTE: each single whitespace and newline close to the template is important!
# - the script might stop to request an interactive confirmation of the host signature
# - it's expected to run this as user 'jenkins' as it will have the right keys setup 

transfer() {
   scp ~/.ssh/github-key $DESTINATION:~/.ssh
   scp ~/.ssh/id_dsa_sourceforge $DESTINATION:~/.ssh
   scp ~/.ssh/id_dsa_filemgmt_jboss_org $DESTINATION:~/.ssh
}

for DESTINATION in {% for host in groups['cislaves'] %}"{{ host }}" {% endfor %}

do
   transfer
done

for DESTINATION in {% for host in groups['awscislaves'] %}"{{ hostvars[host]['private_ip'] }}" {% endfor %}

do
   transfer
done
