---

- name: Extra packages required on worker nodes
  dnf:
    name: ['java-11-openjdk-devel', 'git', 'patch', 'policycoreutils-python-utils']
    state: present
  tags:
    - extra-packages

- name: Create Docker group
  group:
    name: docker
    state: present
  tags:
    - docker
    - groups

- name: Assign docker groups to jenkins
  user: name=jenkins groups=docker append=yes
  tags:
    - docker
    - groups

- name: Install Docker engine and Docker Compose
  dnf:
    name: ['moby-engine', 'docker-compose']
    state: present
  tags:
    - docker

# Just in case the worker node does not get anything mounted to /mnt/workdir
- name: Create /mnt/workdir/containers
  file: path=/mnt/workdir/containers owner=root group=root mode=0600 state=directory
  tags:
    - docker

- name: Create /etc/docker
  file: path=/etc/docker owner=root group=root mode=0600 state=directory
  tags:
    - docker

- name: Use /mnt/workdir/containers for Docker data
  copy: src=etc/docker/daemon.json dest=/etc/docker/daemon.json mode=0600 owner=root group=root
  tags:
    - docker

- name: Start Docker
  service: name=docker enabled=yes state=started
  tags:
    - docker

- name: Enable SERVICES Cmnd_Alias
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: 'Cmnd_Alias SERVICES'
    line: 'Cmnd_Alias SERVICES = /sbin/service, /sbin/chkconfig'
    validate: 'visudo -cf %s'
  tags:
    - services

- name: Give jenkins permission to run docker
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^jenkins ALL='
    line: 'jenkins ALL=(ALL) NOPASSWD: SERVICES, /usr/bin/docker, /usr/bin/docker-compose'
    validate: 'visudo -cf %s'
  tags:
    - services

# Just in case the worker node does not get anything mounted to /mnt/workdir
- name: Create /mnt/workdir/jenkins
  file: path=/mnt/workdir/jenkins owner=jenkins group=jenkins mode=0755 state=directory
  tags:
    - jenkins

- name: Create link /var/lib/jenkins to /mnt/workdir/jenkins
  file: path=/var/lib/jenkins src=/mnt/workdir/jenkins owner=jenkins group=jenkins mode=0755 state=link force=yes
  tags:
    - jenkins

# Some CI jobs need to run rsync on in.relation.to,
# this will ensure in.relation.to is added to the known_host
# The ssh-keyscan approach (controversial!) is inspired from: http://hakunin.com/six-ansible-practices
- name: Ensure in.relation.to is a known host
  lineinfile:
    dest: /home/jenkins/.ssh/inrelationto-knownhosts
    create: yes
    state: present
    owner: jenkins
    group: jenkins
    mode: 0600
    line: "{{ lookup('pipe', 'ssh-keyscan -t ecdsa in.relation.to') }}"
    regexp: "^in.relation.to"
  tags:
    - create-known-hosts
