---
- name: Extra packages required on instance-storage nodes
  dnf:
    name: ['policycoreutils-python-utils']
    state: present
  tags:
    - extra-packages

- name: Copy mount_workdir script file
  copy: src=usr/local/bin/mount_workdir.sh dest=/usr/local/bin/mount_workdir.sh owner=root group=root mode=0500
  tags:
    - docker

- name: Copy init_workdir script file
  template: src=usr/local/bin/init_workdir.sh dest=/usr/local/bin/init_workdir.sh owner=root group=root mode=0500
  tags:
    - docker

- name: Copy mount_workdir service file
  copy: src=etc/systemd/system/mount_workdir.service dest=/etc/systemd/system/mount_workdir.service owner=root group=root mode=0440
  tags:
    - docker

- name: Ensure mount_workdir.service is started now, and again on startup
  systemd: name=mount_workdir enabled=yes state=started
  tags:
    - docker
  notify:
    - Restart Docker
